version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_ARGS=--appendonly yes --appendfsync everysec --protected-mode no
    # command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec", "--protected-mode" , "no"]
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  trading-engine:
    image: python:3.10
    container_name: trading-engine
    working_dir: /app
    volumes:
      - ./:/app
    command: /bin/bash -c "pip install uv && uv run python -m cli.main start --config-path config/config.yaml"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    image: python:3.10
    container_name: backend
    working_dir: /app
    volumes:
      - ./app/tradingview_dashboard/backend:/app
    command: /bin/bash -c "pip install pipx && pipx install . && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./app/tradingview_dashboard/frontend:/app
    command: /bin/bash -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

volumes:
  redis-insight:
  redis-data:
